import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ResponsiveAppBar from "./_components/app_bar";
import {BottomNavigation, BottomNavigationAction, CssBaseline} from "@mui/material";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function RestoreIcon() {
    return null;
}

function FavoriteIcon() {
    return null;
}

function LocationOnIcon() {
    return null;
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <script src="https://telegram.org/js/telegram-web-app.js" async />
        </head>
        <CssBaseline/>
        <body className={inter.className}>
        <ResponsiveAppBar/>
        {children}
        </body>
        </html>
    );
}
